### ISSUE TITLE
Undefined is not an object (evaluating 'StripeModule.init') issue in Android 

### ISSUE THREAD

**Issue by SreekanthOAuth** [tipsi/tipsi-stripe#250]
Getting this exception while trying to link tipsi-stripe in both auto and manual ways.

Using,
Android Studio 3.0.1
react-native-cli: 2.0.1
react-native: 0.54.0

**Comment by isnifer** [comment]
So, you didn't link tipsi-stripe. Show me your diff – how did you do that?

**Comment by SreekanthOAuth** [comment]
Hi isnifer - Didn't get your reply. Are you asking about the installation steps? If so, followed the https://github.com/tipsi/tipsi-stripe#android-1

**Comment by isnifer** [comment]
@SreekanthOAuth so, if you followed these steps — you shouldn't get this error. Please, recheck it and tell me where you were wrong)

**Comment by SreekanthOAuth** [comment]
Hi isnifer , we have tried again but still getting the same error. 

We only using auto way i.e., requesting the react-native link tipsi-stripe' command. Please let me know if any other things need to be validated before we link this.

**Comment by isnifer** [comment]
@SreekanthOAuth create a new clean project on the github — link `tipsi-stripe` like you did before and show me this project. We will what you did wrong

**Comment by tmaly1980** [comment]
Was init() renamed to setOptions() at some point? The docs mention calling init() but the Stripe.<platform>.js file only has setOptions() - which calls TPSStripeManager.init() . I've done a grep and there is no reference to init() except inside setOptions()

**Comment by cybergrind** [comment]
@tmaly1980 and we even have PR with updated readme #260
Still waiting for review to merge it

**Comment by tmaly1980** [comment]
How long ago was this renamed? Someone needs to either do their job as repo maintainer or give write access to someone else.

**Comment by cybergrind** [comment]
It was renamed in v5.0.0 update. Currently, @isnifer is doing maintainer work if you want to join him - I'll glad to add you.

**Comment by isnifer** [comment]
@cybergrind we are ready to merge updated docs and CHANGELOG.md https://github.com/tipsi/tipsi-stripe/pull/260

**Comment by LivanDiaz** [comment]
----TypeError: undefines is not an object (evaluating 'StripeModule.init') ---- im getting the same error in IOS ... using expo-payments-stripe "version": "8.1.0" ...
in Android it works ....

**Comment by chetanCyquent** [comment]
Hi @LivanDiaz,

What changes made in android project to get it work.
I am facing this issue for both (android and iOS)
and I fixed iOS by adding following in `podfile` in ios.

`pod 'Stripe', '>= 19.0.1'
pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'`

your help on android will be highly appreciated.

I am using this on following config,
React: 16.11.0
React-Native: 0.62.2
tipsi-stripe: 8.0.0-beta.10

Thanks

**Comment by LivanDiaz** [comment]
> Hi @LivanDiaz,
> 
> What changes made in android project to get it work.
> I am facing this issue for both (android and iOS)
> and I fixed iOS by adding following in `podfile` in ios.
> 
> `pod 'Stripe', '>= 19.0.1' pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'`
> 
> your help on android will be highly appreciated.
> 
> I am using this on following config,
> React: 16.11.0
> React-Native: 0.62.2
> tipsi-stripe: 8.0.0-beta.10
> 
> Thanks

Hi chetanCyquent, I am using Expo (expo-payments-stripe) ... it really worked for me on android when I followed all the documentation steps in (https://docs.expo.io/versions/v38.0.0/sdk/ payments / # register-hook-in-order-to-let-stripe) but I still have the same error on IOS ... I'm considering using tipsi-stripe although I think that in one of my tests I got the same error, maybe Between the two of us we can solve it, do you have Telegram, WhatsApp or something like that where we can communicate ???

**Comment by pheN1x** [comment]
Hello, im having the same issue...
